version: '3.8'

services:
  mysql_db:
    image: mysql:8.0
    container_name: coworking_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: moscow_coworkings
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - ./sql_scripts:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password